### ISSUE TITLE
amd

### ISSUE THREAD

**Issue by fwf02** [KilianKegel/Visual-TSCSync-for-UEFI-Shell#3]
is it possible to have amd version as well or its only intel

**Comment by KilianKegel** [comment]
It runs on AMD as well...

**Comment by fwf02** [comment]
hey how its determine processor speed  for amd ? its should be start from 0xc0010064 msr P0 frequency

**Comment by KilianKegel** [comment]
The ACPI Timer runs at 3.579545 MHz on all ACPI enabled systems, AMD and Intel!!!
https://uefi.org/sites/default/files/resources/ACPI_Spec_6_4_Jan22.pdf#page=130

Waiting 3579545 ACPI clocks and subtracting TSCEnd from TSCStart gives you the CPU speed in Hz.
Waiting 3579545 / 20 ACPI clocks and subtracting TSCEnd from TSCStart, multiplied by 20, gives you the CPU speed in Hz,
but you have also multiplied the measurement error by 20.

This is relation is reflected in the excel diagrams, when selecting different synchronization times.

**Comment by fwf02** [comment]
sorry for reopen this on amd we could add __svm_clgi which Clears the global interrupt flag and __svm_stgi restore it it will improve the measurements of  the frequency   in amd  its required svm mode enabled  and enable 0xC0000080 msr  bit 12 to be 1  SVME (Secure Virtual Machine Enable)

**Comment by KilianKegel** [comment]
Hmm, UEFI programs and drivers usually runs non-virtualized, except with OVFM. My work just demonstrates that one can do precise time measurement once the reference timer is synchronized long enough. Instead TIANOCORE synchronizes 101us and multiplies by 9861 https://github.com/tianocore/edk2/blob/master/PcAtChipsetPkg/Library/AcpiTimerLib/AcpiTimerLib.c#L390
and than gets a unusable timebase...
